Feature/5 dev first version of charts
akvo/akvo-charts pull request #7
Opened 2024-07-24 10:30 UTC by wayangalihpratama

2024-07-26 09:40 UTC, dedenbangkit requested changes
Where is the Doughnut.js? Doughnut can also inherit from Bar.js

2024-07-26 09:40 UTC, dedenbangkit commented on src/components/__tests__/Bar.test.js
> +  const data = [
Please add this in the Readme

2024-07-26 09:40 UTC, dedenbangkit commented on src/components/__tests__/Bar.test.js
> +  const config = {
also this part

2024-07-26 09:44 UTC, wayangalihpratama commented
> Where is the Doughnut.js? Doughnut can also inherit from Bar.js

Doughnut chart is in Pie.js, should we separate Pie and Doughnut?

2024-07-28 23:45 UTC, dedenbangkit approved these changes

2024-07-28 23:45 UTC, merged